name = "desbord"
compatibility_date = "2024-09-23"
compatibility_flags = [
  "nodejs_compat_v2",
]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
preview_database_id = "DB"
database_name = "desbord"
database_id = "c1e8d1da-1c79-4bfb-9250-9e655a9f5499"
migrations_dir = ".drizzle/migrations"
