name = "desbord"
compatibility_date = "2024-09-23"
compatibility_flags = [
  "nodejs_compat_v2",
]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
preview_database_id = "DB"
database_name = "desbord"
database_id = "8b48fb38-df3a-4ee2-aacf-403020d75b77"
migrations_dir = ".drizzle/migrations"
